name: '[builder] CI for releases'

on:
  push:
    branches:
      - main
#      - grpc-for-mobile-unit

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dockerhub login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin

      #      - name: Login to Docker Hub
      #        uses: docker/login-action@v2
      #        with:
      #          username: ${{ secrets.DOCKERHUB_USERNAME }}
      #          password: ${{ secrets.DOCKER_PASSWORD }}

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          config: .github/buildkitd.toml

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            mvniekerk/rustc-protoc:latest
          platforms: linux/amd64
          cache-from: type=registry,ref=mvniekerk/rustc-protoc:latest
          cache-to: type=inline
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.ACTIONS_SSH }}
          ssh: |
            default=${{ env.SSH_AUTH_SOCK }}
            github.com=${{ env.SSH_AUTH_SOCK }}

